apiVersion: v1
kind: Service
metadata:
  name: spindrift-app
spec:
  type: LoadBalancer  # Expose the service externally
  ports:
    - port: 3000        # External port for clients
      targetPort: 3000  # Port the app listens on inside the containers
  selector:
    app: spindrift-app  # Match the app label
