name: "Terraform CI/CD"

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the `main` branch

jobs:
  terraform:
    name: "Run Terraform"
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository code
      - name: "Check out repository"
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"  # Specify the version of Terraform to use

      # Step 3: Configure AWS credentials (example for AWS)
      - name: "Set up AWS credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      # Step 4: Install Terraform providers (if necessary)
      - name: "Install Terraform providers"
        run: terraform init
        working-directory: ./terraform

      # Step 5: Format the Terraform code (optional but recommended)
      - name: "Terraform Format"
        run: terraform fmt -check -diff

      # Step 6: Validate the Terraform code
      - name: "Terraform Validate"
        run: terraform validate
        working-directory: ./terraform

      # Step 7: Plan the Terraform execution (this is a dry run to show changes)
      - name: "Terraform Plan"
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      # Step 8: Apply the Terraform plan (Deploy infrastructure)
      - name: "Terraform Apply"
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform

      # Step 9: Wait for 10 minutes (Pause for manual inspection)
      - name: "Wait for 10 minutes to check the website"
        run: sleep 600  # Sleep for 600 seconds (10 minutes)

      # Step 10: Destroy Terraform infrastructure after inspection
      - name: "Terraform Destroy"
        run: terraform destroy -auto-approve
        working-directory: ./terraform
